server:
  port: 8085

spring:
  application:
    name: zuul-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    a:
      path: /a/**
      serviceId: feign-consumer
    b:
      path: /b/**
      serviceId: ribbon-consumer
    c:
      path: /c/**
      url: https://www.baidu.com